services:
  web:
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio.rule=Host(`v1.jcs.works`)
      - traefik.http.routers.portfolio.entrypoints=websecure
      - traefik.http.services.portfolio.loadbalancer.server.port=80
networks:
  proxy:
    external: true

